### ISSUE TITLE
RuntimeError: mat1 dim 1 must match mat2 dim 0

### ISSUE THREAD

**Issue by hongminglin08** [joslefaure/HIT_ava#2]
![image](https://github.com/joslefaure/HIT_ava/assets/52478955/60d0ee84-9ab1-4f5b-9018-48f9ebfd7043)

**Comment by joslefaure** [comment]
That's not reproducible. Are you training on the AVA dataset? This is probably an issue with the number of classes

**Comment by joslefaure** [comment]
Fixed in the latest commit. Thanks for raising the issue
