### ISSUE TITLE
Video mAP on AVA dataset

### ISSUE THREAD

**Issue by Cogito2012** [joslefaure/HIT_ava#4]
Hi,

Thanks for sharing such a great repo! 
Could you tell me how to implement the video mAP evaluation on the AVA dataset? 

The videoAP function from the other repo [here](https://github.com/joslefaure/HIT/blob/9ac007840ca76d19140a1b3d619eda1c9ae4c52e/evaluation_ucf24_jhmdb/compute_video_map.py#L156) seems to be only applicable to JHMDB or UCF24 dataset. Since the bounding boxes of the AVA dataset could be associated with multiple action labels, and the structure of annotation is significantly different,  the videoAP function may have to be modified. So, any instructions on the modification would be helpful a lot! 

Thank you!

**Comment by joslefaure** [comment]
It will be automatically calculated
